root:
  askformore: false
  autoimport: true
  autosync: false
  cliptimeout: 45
  noconfirm: true
  nopager: false
  path: /home/michele/.password-store
  safecontent: false
  usesymbols: false
  nocolor: true
mounts: {}
version: 1.6.9-git+HEAD
